---
- name: Install generic OIM
  hosts: all
  remote_user: "{{ user_for_oim }}"
  tags: install

  vars_prompt:
    - name: "user_for_oim"
      prompt: "Please enter the username (without sudo)"
      private: no

  tasks:
  - copy:
      src: ./install.sh
      dest: $HOME
      owner: "{{ user_for_oim }}"
      mode: 0755
      force: yes

  - name: Install generic OIM
    command: bash install.sh

  # The memory setting is in the bash install script, this is not used but is kept if needed later.
  # - name: Increase memory to 3G (backup)
  #   lineinfile: 
  #     path: $HOME/openinfoman/bin/basexhttp
  #     regexp: '^BASEX_JVM='
  #     line: 'BASEX_VM="-Xms3g -Xmx3g" $BASEX_JVM"'      