---
- name: Install generic OIM
  hosts: all
  become: true
  become_user: "{{ user_for_oim }}"
  tags: install

  vars_prompt:
    - name: "user_for_oim"
      prompt: "Please enter the username (without sudo) for installing and running for OIM"
      private: no

  tasks:
  - copy:
      src: ./install.sh
      dest: $HOME
      owner: "{{ user_for_oim }}"
      mode: 0755
      force: yes

  - name: Install generic OIM
    command: bash install.sh