---
- name: Install DATIM modules for OIM
  hosts: all
  remote_user: "{{ user_for_oim }}"
  tags: install-datim

  vars_prompt:
    - name: "user_for_oim"
      prompt: "Please enter the username (without sudo)"
      private: no

  tasks:
  - copy:
      src: ./install_datim.sh
      dest: $HOME
      owner: "{{ user_for_oim }}"
      mode: 0755
      force: yes

  - name: Install DATIM modules for OIM
    command: bash install_datim.sh