---
- name: Preparation for OIM
  hosts: all
  remote_user: "{{ user_for_oim }}"
  tags: backup

  vars_prompt:
    - name: "user_for_oim"
      prompt: "Please enter the username (without sudo) for installing and running for OIM"
      private: no

  tasks:
    - name: Does data/logs folder exist
      stat:
        path: ~/openinfoman/data
      register: stat_result

    - debug:
        msg: "OpenInfoMan folder does not have data/logs dir"
      when: stat_result.stat.exists == False

    - name: Backup OIM data dir.
      shell: basex -c"CREATE BACKUP provider_directory"
      when: stat_result.stat.exists == False

    - name: Backup OIM data dir.
      shell: zip $HOME/openinfoman/data/logs-$(date +"%Y-%m-%d-%H-%M").zip $HOME/openinfoman/data/.logs
      when: stat_result.stat.exists == False

    - debug:
        msg: "OpenInfoMan folder has data/logs dir"
      when: stat_result.stat.exists == True

    # - script: ./install_oim-1.4.49.sh